{
 "title": "Pod Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   { "name": "gp", "query": { "query": "label_values(pod)" } },
   { "name": "pod", "query": "None" },
   { "name": "namespace", "label": "ns", "query": { "query": "label_values(namespace)" } },
   {
    "name": "gpn",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "gv",
    "query": {
     "query": "label_values(persistentvolumeclaim)"
    }
   },
   { "name": "percentage", "label": "%" }
  ]
 },
 "panels": [
  {
   "title": "Get Pod info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get pod info",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "kube_pod_info{pod=~\"$gp|$pod.*\"}",
       "legendFormat": "pod: {{pod}}, namespace: {{namespace}}, pod_ip: {{pod_ip}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  { "title": "All Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Pod Memory All",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(pod)(container_memory_usage_bytes{pod=~\"$pod.*|$gp\", pod!~\".*prometheus-0\"}) / avg by(pod)(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$pod.*|$gp\"}) \n* 100 $percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU All",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod.*|$gp\", pod!~\".*prometheus-0\"}[2m])) / avg by(pod)(kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"$pod.*|$gp\"}) * 100 $percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container restart All",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{pod=~\"$pod.*|$gp\"}[1h]) > 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PV All",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$gv\"})/(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$gv\" }) * 100 $percentage",
     "legendFormat": "{{persistentvolumeclaim}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Pods with namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "pod Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(pod)(container_memory_usage_bytes{pod=~\"$pod.*|$gp\", namespace=\"$namespace\"}) / avg by(pod)(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$pod.*|$gp\", namespace=\"$namespace\"}) \n* 100 $percentage",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod.*|$gp\", namespace=\"$namespace\"}[2m])) / avg by(pod)(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$pod.*|$gp\", namespace=\"$namespace\", }) * 100 $percentage",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PV All",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$gv\", namespace=\"$namespace\"})/(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$gv\", namespace=\"$namespace\" }) * 100 $percentage",
       "legendFormat": "{{persistentvolumeclaim}} - {{namespace}}"
      }
     ]
    },
    {
     "title": "Container Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(container)(container_memory_usage_bytes{container=\"$pod\", pod=\"$gp\", namespace=\"$namespace\"}) / avg by(container)(kube_pod_container_resource_limits{resource=\"memory\", container=\"$pod\", pod=\"$gp\", namespace=\"$namespace\"}) \n* 100 $percentage",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Container restart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(kube_pod_container_status_restarts_total{pod=~\"$pod.*|$gp\", namespace=\"$namespace\"}[1h]) > 1",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}